# Generated by Django 5.0.1 on 2025-10-05 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('register', 'Регистрация'), ('test_start', 'Начало тестирования'), ('test_complete', 'Завершение тестирования'), ('enrollment', 'Зачисление подданного'), ('test_pass', 'Прохождение теста'), ('test_fail', 'Неудачное прохождение теста')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
                'db_table': 'action_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
