# Generated by Django 5.0.1 on 2025-10-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
