# Generated by Django 5.0.1 on 2025-10-05 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kingdom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='king',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='king_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='king',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizens', to='kingdom.king', verbose_name='Король'),
        ),
        migrations.AddField(
            model_name='king',
            name='kingdom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='king', to='kingdom.kingdom', verbose_name='Королевство'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='kingdom.kingdom', verbose_name='Королевство'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='kingdom.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='test',
            name='kingdom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='kingdom.kingdom', verbose_name='Королевство'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='kingdom.test', verbose_name='Тестовое испытание'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='kingdom.citizen', verbose_name='Подданный'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='kingdom.test', verbose_name='Тестовое испытание'),
        ),
        migrations.AddField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='kingdom.testattempt', verbose_name='Попытка'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
